version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    env_file:
      - cmd/auction/.env
    depends_on:
      - mongodb
    networks:
      - localNetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - cmd/auction/.env
    volumes:
      - mongo-data:/data/db
    networks:
      - localNetwork

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - cmd/auction/.env
    environment:
      - MONGODB_URL=mongodb://admin:admin@mongodb:27017/auctions_test?authSource=admin
      - MONGODB_DB=auctions_test
      - AUCTION_DURATION=2s
    depends_on:
      - mongodb
    profiles:
      - test
    networks:
      - localNetwork

volumes:
  mongo-data:
    driver: local

networks:
  localNetwork:
    driver: bridge
